#ifndef __M68KINTERNAL_AMODES_H__
#define __M68KINTERNAL_AMODES_H__

// bits in the "brief extension word"
// 
//      bit     5432109876543210
//              abbbcdd0
//                      eeeeeeee
//
//      a       type of index register:
//              0 = data register
//              1 = address register
//
//      bbb     index for the register (0-7)
//
//      c       size for register: 
//              0 = word (sign-extended)
//              1 = long
//
//      dd      scale:
//              00 = 1
//              01 = 2
//              10 = 4
//              11 = 8
//
//      e..e    8-bit signed displacement
//
// bits in the "full extension word"
//
//      bit     5432109876543210
//              abbbcdd1
//                      efgg0hhh
//
//      a       type of index register:
//              0 = data register
//              1 = address register
//
//      bbb     index for the register (0-7)
//
//      c       size for register: 
//              0 = word (sign-extended)
//              1 = long
//
//      dd      scale:
//              00 = 1
//              01 = 2
//              10 = 4
//              11 = 8
//
//      e       base register is suppressed: 
//              0 = no
//              1 = yes
//
//      f       index register is suppressed:
//              0 = no
//              1 = yes
//
//      gg      size of base displacement:
//              00 = reserved
//              01 = not used
//              10 = word displacement
//              11 = long displacement
//
//      hhh     specifies the memory type and the outer displacement:
//              f hhh
//              x 000   no memory indirect action i.e. (d32, An, Xn.SIZE * SCALE) where d32(gg), An(e) and Xn(f) are optional; if all elements are optional we end up with [0]
//              0 0??   memory indirect pre-indexed:
//                      01 = without outer displacement
//                      10 = 16-bit outer displacement 
//                      11 = 32-bit outer displacement 
//                      i.e. ([d32i, An, Xn.SIZE * SCALE], d32o) where d32i(gg), An(e) and d32o(??) are optional
//              0 100   reserved
//              0 1??   memory indirect post-indexed:
//                      01 = without outer displacement
//                      10 = 16-bit outer displacement 
//                      11 = 32-bit outer displacement 
//                      i.e. ([d32i, An], Xn.SIZE * SCALE, d32o) where d32i(gg), An(e) and d32o(??) are optional
//              1 0??   memory indirect pre-indexed:
//                      01 = without outer displacement
//                      10 = 16-bit outer displacement 
//                      11 = 32-bit outer displacement 
//                      i.e. ([d32i, An], d32o) where d32i(gg), An(e) and d32o(??) are optional; if all elements are optional we end up with [[0]]

typedef enum ADDRESSING_MODE_TYPE
{
    AMT_DATA_REGISTER_DIRECT                            = 0x00000001UL, // Dn
    AMT_ADDRESS_REGISTER_DIRECT                         = 0x00000002UL, // An
    AMT_ADDRESS_REGISTER_INDIRECT                       = 0x00000004UL, // (An)
    AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT        = 0x00000008UL, // (An)+
    AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT         = 0x00000010UL, // -(An)
    AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT          = 0x00000020UL, // (d16, An)
    AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B  = 0x00000040UL, // (d8, An, Xn.SIZE * SCALE)
    AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L  = 0x00000080UL, // (d32, An, Xn.SIZE * SCALE)
    AMT_MEMORY_INDIRECT_POST_INDEXED                    = 0x00000100UL, // ([d32i, An], Xn.SIZE * SCALE, d32o)
    AMT_MEMORY_INDIRECT_PRE_INDEXED                     = 0x00000200UL, // ([d32i, An, Xn.SIZE * SCALE], d32o)
    AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT           = 0x00000400UL, // (d16, PC)
    AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B   = 0x00000800UL, // (d8, PC, Xn.SIZE * SCALE) 
    AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L   = 0x00001000UL, // (d32, PC, Xn.SIZE * SCALE)
    AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED    = 0x00002000UL, // ([d32i, PC], Xn.SIZE * SCALE, d32o)
    AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED     = 0x00004000UL, // ([d32i, PC, Xn.SIZE * SCALE], d32o)
    AMT_ABSOLUTE_SHORT                                  = 0x00008000UL, // (xxx).w
    AMT_ABSOLUTE_LONG                                   = 0x00010000UL, // (xxx).l
    AMT_IMMEDIATE_DATA                                  = 0x00020000UL, // #xxx
    AMT_ADDRESS_REGISTER_INDIRECT_P20H                  = 0x00040000UL, // An for 68020 or higher
    AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H      = 0x00080000UL, // (d16, PC) for 68020 or higher
    AMT_IMMEDIATE_DATA_P20H                             = 0x00100000UL, // #xxx for 68020 or higher
    AMT__ALL__                                          = 0x0003ffffUL,

    AMT__AC80_ALL__ = AMT__ALL__,

    AMT__AC80_ALTERABLE__ =
        AMT_DATA_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__ALTERABLE__ =
        AMT_DATA_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__CONTROL__ = 
        // AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        // AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        // AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__CONTROL_ALTERABLE__ = 
        // AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        // AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        // AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__DATA__ =
        AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__DATA_ALTERABLE__ = 
        AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__DATA_ALTERABLE_PC__ =
        AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,
        
    AMT__DATA_ALTERABLE_MEMORY__ = 
        // AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__DATA_REGISTER_DIRECT_CONTROL_ALTERABLE__ = 
        AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        // AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        // AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__MEMORY_ALTERABLE__ = 
        // AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT | 
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT | 
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT | 
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT | 
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B | 
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__PFR__ =
        // AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__TST__ =
        AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT |
        AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        AMT_ABSOLUTE_SHORT |
        AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        AMT_IMMEDIATE_DATA_P20H |
        0,

    AMT__TOUCH__ =
        // AMT_DATA_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_DIRECT |
        // AMT_ADDRESS_REGISTER_INDIRECT |
        // AMT_ADDRESS_REGISTER_INDIRECT_POST_INCREMENT |
        // AMT_ADDRESS_REGISTER_INDIRECT_PRE_DECREMENT |
        // AMT_ADDRESS_REGISTER_INDIRECT_DISPLACEMENT |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_B |
        AMT_ADDRESS_REGISTER_INDIRECT_INDEX_DISPLACEMENT_L |
        AMT_MEMORY_INDIRECT_POST_INDEXED |
        AMT_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_B |
        // AMT_PROGRAM_COUNTER_INDIRECT_INDEX_DISPLACEMENT_L |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_POST_INDEXED |
        // AMT_PROGRAM_COUNTER_MEMORY_INDIRECT_PRE_INDEXED |
        // AMT_ABSOLUTE_SHORT |
        // AMT_ABSOLUTE_LONG |
        // AMT_IMMEDIATE_DATA |
        // AMT_ADDRESS_REGISTER_INDIRECT_P20H |
        // AMT_PROGRAM_COUNTER_INDIRECT_DISPLACEMENT_P20H |
        // AMT_IMMEDIATE_DATA_P20H |
        0,
} ADDRESSING_MODE_TYPE, *PADDRESSING_MODE_TYPE;

typedef M68K_DWORD ADDRESSING_MODE_TYPE_VALUE, *PADDRESSING_MODE_TYPE_VALUE;

#endif
