#include "m68kinternal.h"

// table with the index of first words for each master instruction type
M68KC_WORD _M68KAsmIndexFirstWord[M68K_IT__SIZEOF__ - 1] =
{
#include "gen/index_first_words.h"
};

// table with the mnemonic aliases
M68K_CONST MNEMONIC_ALIAS _M68KAsmMnemonicAliases[MAT__SIZEOF__] =
{
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_CC    }, // MAT_BCC
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_CS    }, // MAT_BCS
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_EQ    }, // MAT_BEQ
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_GE    }, // MAT_BGE
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_GT    }, // MAT_BGT
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_HI    }, // MAT_BHI
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_HS    }, // MAT_BHS
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LE    }, // MAT_BLE
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LO    }, // MAT_BLO
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LS    }, // MAT_BLS
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LT    }, // MAT_BLT
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_MI    }, // MAT_BMI
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_NE    }, // MAT_BNE
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_PL    }, // MAT_BPL
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_VC    }, // MAT_BVC
    {M68K_IT_BCC        , M68K_OT_CONDITION_CODE        , M68K_CC_VS    }, // MAT_BVS

    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_CC    }, // MAT_DBCC
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_CS    }, // MAT_DBCS
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_EQ    }, // MAT_DBEQ
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_F     }, // MAT_DBF
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_GE    }, // MAT_DBGE
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_GT    }, // MAT_DBGT
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_HI    }, // MAT_DBHI
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_HS    }, // MAT_DBHS
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_LE    }, // MAT_DBLE
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_LO    }, // MAT_DBLO
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_LS    }, // MAT_DBLS
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_LT    }, // MAT_DBLT
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_MI    }, // MAT_DBMI
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_NE    }, // MAT_DBNE
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_PL    }, // MAT_DBPL
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_F     }, // MAT_DBRA
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_T     }, // MAT_DBT
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_VC    }, // MAT_DBVC
    {M68K_IT_DBCC       , M68K_OT_CONDITION_CODE        , M68K_CC_VS    }, // MAT_DBVS
    
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_EQ  }, // MAT_FBEQ
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_F   }, // MAT_FBF
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GE  }, // MAT_FBGE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GL  }, // MAT_FBGL
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GLE }, // MAT_FBGLE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GT  }, // MAT_FBGT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LE  }, // MAT_FBLE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LT  }, // MAT_FBLT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NE  }, // MAT_FBNE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGE }, // MAT_FBNGE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGL }, // MAT_FBNGL
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGLE}, // MAT_FBNGLE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGT }, // MAT_FBNGT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLE }, // MAT_FBNLE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLT }, // MAT_FBNLT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGE }, // MAT_FBOGE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGT }, // MAT_FBOGT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLE }, // MAT_FBOLE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLG }, // MAT_FBOLG
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLT }, // MAT_FBOLT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OR  }, // MAT_FBOR
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SEQ }, // MAT_FBSEQ
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SF  }, // MAT_FBSF
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SNE }, // MAT_FBSNE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ST  }, // MAT_FBST
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_T   }, // MAT_FBT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UEQ }, // MAT_FBUEQ
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGE }, // MAT_FBUGE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGT }, // MAT_FBUGT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULE }, // MAT_FBULE
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULT }, // MAT_FBULT
    {M68K_IT_FBCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UN  }, // MAT_FBUN
    
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_EQ  }, // MAT_FDBEQ
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_F   }, // MAT_FDBF
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GE  }, // MAT_FDBGE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GL  }, // MAT_FDBGL
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GLE }, // MAT_FDBGLE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GT  }, // MAT_FDBGT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LE  }, // MAT_FDBLE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LT  }, // MAT_FDBLT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NE  }, // MAT_FDBNE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGE }, // MAT_FDBNGE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGL }, // MAT_FDBNGL
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGLE}, // MAT_FDBNGLE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGT }, // MAT_FDBNGT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLE }, // MAT_FDBNLE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLT }, // MAT_FDBNLT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGE }, // MAT_FDBOGE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGT }, // MAT_FDBOGT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLE }, // MAT_FDBOLE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLG }, // MAT_FDBOLG
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLT }, // MAT_FDBOLT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OR  }, // MAT_FDBOR
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SEQ }, // MAT_FDBSEQ
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SF  }, // MAT_FDBSF
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SNE }, // MAT_FDBSNE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ST  }, // MAT_FDBST
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_T   }, // MAT_FDBT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UEQ }, // MAT_FDBUEQ
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGE }, // MAT_FDBUGE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGT }, // MAT_FDBUGT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULE }, // MAT_FDBULE
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULT }, // MAT_FDBULT
    {M68K_IT_FDBCC      , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UN  }, // MAT_FDBUN
    
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_EQ  }, // MAT_FSEQ
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_F   }, // MAT_FSF
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GE  }, // MAT_FSGE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GL  }, // MAT_FSGL
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GLE }, // MAT_FSGLE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GT  }, // MAT_FSGT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LE  }, // MAT_FSLE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LT  }, // MAT_FSLT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NE  }, // MAT_FSNE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGE }, // MAT_FSNGE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGL }, // MAT_FSNGL
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGLE}, // MAT_FSNGLE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGT }, // MAT_FSNGT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLE }, // MAT_FSNLE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLT }, // MAT_FSNLT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGE }, // MAT_FSOGE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGT }, // MAT_FSOGT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLE }, // MAT_FSOLE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLG }, // MAT_FSOLG
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLT }, // MAT_FSOLT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OR  }, // MAT_FSOR
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SEQ }, // MAT_FSSEQ
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SF  }, // MAT_FSSF
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SNE }, // MAT_FSSNE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ST  }, // MAT_FSST
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_T   }, // MAT_FST
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UEQ }, // MAT_FSUEQ
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGE }, // MAT_FSUGE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGT }, // MAT_FSUGT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULE }, // MAT_FSULE
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULT }, // MAT_FSULT
    {M68K_IT_FSCC       , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UN  }, // MAT_FSUN
    
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_T   }, // MAT_FTRAP
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_EQ  }, // MAT_FTRAPEQ
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_F   }, // MAT_FTRAPF
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GE  }, // MAT_FTRAPGE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GL  }, // MAT_FTRAPGL
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GLE }, // MAT_FTRAPGLE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_GT  }, // MAT_FTRAPGT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LE  }, // MAT_FTRAPLE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_LT  }, // MAT_FTRAPLT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NE  }, // MAT_FTRAPNE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGE }, // MAT_FTRAPNGE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGL }, // MAT_FTRAPNGL
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGLE}, // MAT_FTRAPNGLE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NGT }, // MAT_FTRAPNGT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLE }, // MAT_FTRAPNLE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_NLT }, // MAT_FTRAPNLT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGE }, // MAT_FTRAPOGE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OGT }, // MAT_FTRAPOGT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLE }, // MAT_FTRAPOLE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLG }, // MAT_FTRAPOLG
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OLT }, // MAT_FTRAPOLT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_OR  }, // MAT_FTRAPOR
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SEQ }, // MAT_FTRAPSEQ
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SF  }, // MAT_FTRAPSF
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_SNE }, // MAT_FTRAPSNE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ST  }, // MAT_FTRAPST
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_T   }, // MAT_FTRAPT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UEQ }, // MAT_FTRAPUEQ
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGE }, // MAT_FTRAPUGE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UGT }, // MAT_FTRAPUGT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULE }, // MAT_FTRAPULE
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_ULT }, // MAT_FTRAPULT
    {M68K_IT_FTRAPCC    , M68K_OT_FPU_CONDITION_CODE    , M68K_FPCC_UN  }, // MAT_FTRAPUN
    
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AC }, // MAT_PBAC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AS }, // MAT_PBAS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BC }, // MAT_PBBC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BS }, // MAT_PBBS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CC }, // MAT_PBCC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CS }, // MAT_PBCS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GC }, // MAT_PBGC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GS }, // MAT_PBGS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IC }, // MAT_PBIC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IS }, // MAT_PBIS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LC }, // MAT_PBLC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LS }, // MAT_PBLS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SC }, // MAT_PBSC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SS }, // MAT_PBSS
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WC }, // MAT_PBWC
    {M68K_IT_PBCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WS }, // MAT_PBWS
    
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AC }, // MAT_PDBAC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AS }, // MAT_PDBAS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BC }, // MAT_PDBBC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BS }, // MAT_PDBBS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CC }, // MAT_PDBCC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CS }, // MAT_PDBCS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GC }, // MAT_PDBGC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GS }, // MAT_PDBGS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IC }, // MAT_PDBIC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IS }, // MAT_PDBIS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LC }, // MAT_PDBLC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LS }, // MAT_PDBLS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SC }, // MAT_PDBSC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SS }, // MAT_PDBSS
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WC }, // MAT_PDBWC
    {M68K_IT_PDBCC      , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WS }, // MAT_PDBWS
    
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AC }, // MAT_PSAC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AS }, // MAT_PSAS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BC }, // MAT_PSBC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BS }, // MAT_PSBS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CC }, // MAT_PSCC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CS }, // MAT_PSCS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GC }, // MAT_PSGC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GS }, // MAT_PSGS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IC }, // MAT_PSIC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IS }, // MAT_PSIS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LC }, // MAT_PSLC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LS }, // MAT_PSLS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SC }, // MAT_PSSC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SS }, // MAT_PSSS
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WC }, // MAT_PSWC
    {M68K_IT_PSCC       , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WS }, // MAT_PSWS
    
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AC }, // MAT_PTRAPAC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_AS }, // MAT_PTRAPAS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BC }, // MAT_PTRAPBC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_BS }, // MAT_PTRAPBS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CC }, // MAT_PTRAPCC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_CS }, // MAT_PTRAPCS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GC }, // MAT_PTRAPGC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_GS }, // MAT_PTRAPGS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IC }, // MAT_PTRAPIC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_IS }, // MAT_PTRAPIS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LC }, // MAT_PTRAPLC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_LS }, // MAT_PTRAPLS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SC }, // MAT_PTRAPSC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_SS }, // MAT_PTRAPSS
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WC }, // MAT_PTRAPWC
    {M68K_IT_PTRAPCC    , M68K_OT_MMU_CONDITION_CODE    , M68K_MMUCC_WS }, // MAT_PTRAPWS
    
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_CC    }, // MAT_SCC
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_CS    }, // MAT_SCS
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_EQ    }, // MAT_SEQ
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_F     }, // MAT_SF
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_GE    }, // MAT_SGE
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_GT    }, // MAT_SGT
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_HI    }, // MAT_SHI
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_HS    }, // MAT_SHS
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LE    }, // MAT_SLE
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LO    }, // MAT_SLO
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LS    }, // MAT_SLS
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_LT    }, // MAT_SLT
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_MI    }, // MAT_SMI
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_NE    }, // MAT_SNE
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_PL    }, // MAT_SPL
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_T     }, // MAT_ST
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_VC    }, // MAT_SVC
    {M68K_IT_SCC        , M68K_OT_CONDITION_CODE        , M68K_CC_VS    }, // MAT_SVS
    
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_CC    }, // MAT_TRAPCC
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_CS    }, // MAT_TRAPCS
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_EQ    }, // MAT_TRAPEQ
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_F     }, // MAT_TRAPF
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_GE    }, // MAT_TRAPGE
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_GT    }, // MAT_TRAPGT
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_HI    }, // MAT_TRAPHI
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_HS    }, // MAT_TRAPHS
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_LE    }, // MAT_TRAPLE
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_LO    }, // MAT_TRAPLO
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_LS    }, // MAT_TRAPLS
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_LT    }, // MAT_TRAPLT
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_MI    }, // MAT_TRAPMI
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_NE    }, // MAT_TRAPNE
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_PL    }, // MAT_TRAPPL
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_T     }, // MAT_TRAPT
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_VC    }, // MAT_TRAPVC
    {M68K_IT_TRAPCC     , M68K_OT_CONDITION_CODE        , M68K_CC_VS    }, // MAT_TRAPVS
};

// table with the opcode map mask for each master instruction type
M68KC_WORD _M68KAsmOpcodeMaps[M68K_IT__SIZEOF__- 1] =
{
#include "gen/opcode_maps.h"
};

// table with the words for all master instruction types
M68KC_WORD _M68KAsmWords[] =
{
#include "gen/words.h"
};
