#ifndef __MAIN_H__
#define __MAIN_H__

typedef enum COMMAND_TYPE
{
    CT_UNKNOWN,
    CT_ASSEMBLE_TEXT,
    CT_DISASSEMBLE_BINARY_FILE,
    CT_DISASSEMBLE_NIBBLES,
    CT_DISASSEMBLE_FILE,
    CT_GENERATE_BINARY_FILE,
    CT_GENERATE_HEADER_FILES,
} COMMAND_TYPE, *PCOMMAND_TYPE;

#endif
